import { ExpandableItem } from "../types/components/general";

//=============================================
// Mock Data
//=============================================
const mockData: ExpandableItem[] = [
  {
    title: "Phones",
    ID: 1,
    isSelected: false,
    isExpanded: false,
    type: "Product",
    children: [
      {
        type: "Brand",
        parentID: 1,
        title: "Apple",
        ID: 12,
        isSelected: false,
        isExpanded: false,
        children: [
          {
            type: "Model",
            parentID: 12,
            title: "iPhone 6",
            ID: 121,
            isSelected: false,
            isExpanded: false,
            children: [
              {
                type: "Variant",
                parentID: 121,
                title: "128GB",
                ID: 1211,
                isSelected: false,
                qty: 201,
              },
              {
                type: "Variant",
                parentID: 121,
                title: "256GB",
                ID: 1212,
                isSelected: false,
                qty: 102,
              },
              {
                type: "Variant",
                parentID: 121,
                title: "512GB",
                ID: 1213,
                isSelected: false,
                qty: 51,
              },
            ],
          },
          {
            type: "Model",
            parentID: 12,
            title: "iPhone 7",
            ID: 122,
            isSelected: false,
            isExpanded: false,
            qty: 209,
          },
        ],
      },
      {
        type: "Brand",
        parentID: 1,
        title: "Samsung",
        ID: 11,
        isSelected: false,
        isExpanded: false,
      },
    ],
  },
  {
    type: "Product",
    title: "Watches",
    ID: 3,
    isSelected: false,
    isExpanded: false,
  },
  {
    type: "Product",
    title: "TVs",
    ID: 4,
    isSelected: false,
    isExpanded: false,
    children: [
      {
        type: "Brand",
        parentID: 4,
        title: "Samsung",
        ID: 41,
        isSelected: false,
        isExpanded: false,
        children: [
          {
            type: "Model",
            parentID: 41,
            title: "QLED",
            ID: 411,
            isSelected: false,
            isExpanded: false,
            children: [
              {
                type: "Variant",
                parentID: 411,
                title: "55-inch",
                ID: 4111,
                isSelected: false,
                qty: 201,
              },
              {
                type: "Variant",
                parentID: 411,
                title: "65-inch",
                ID: 4112,
                isSelected: false,
                qty: 102,
              },
              {
                type: "Variant",
                parentID: 411,
                title: "75-inch",
                ID: 4113,
                isSelected: false,
                qty: 51,
              },
            ],
          },
          {
            type: "Model",
            parentID: 41,
            title: "LED",
            ID: 412,
            isSelected: false,
            isExpanded: false,
            qty: 209,
          },
        ],
      },
      {
        type: "Brand",
        parentID: 4,
        title: "Apple",
        ID: 42,
        isSelected: false,
        isExpanded: false,
      },
    ],
  },
  {
    type: "Product",
    title: "Computers",
    ID: 2222222,
    isSelected: false,
    isExpanded: false,
    children: [
      {
        type: "Brand",
        parentID: 2222222,
        title: "Apple",
        ID: 22222221,
        isSelected: false,
        isExpanded: false,
        children: [
          {
            type: "Model",
            parentID: 22222221,
            title: "MacBook Pro",
            ID: 222222211,
            isSelected: false,
            isExpanded: false,
            children: [
              {
                type: "Variant",
                parentID: 222222211,
                title: "13-inch",
                ID: 2222222111,
                isSelected: false,
                qty: 201,
              },
              {
                type: "Variant",
                parentID: 222222211,
                title: "15-inch",
                ID: 2222222112,
                isSelected: false,
                qty: 102,
              },
              {
                type: "Variant",
                parentID: 222222211,
                title: "17-inch",
                ID: 2222222113,
                isSelected: false,
                qty: 51,
              },
            ],
          },
          {
            type: "Model",
            parentID: 22222221,
            title: "MacBook Air",
            ID: 222222212,
            isSelected: false,
            isExpanded: false,
            qty: 209,
          },
        ],
      },
      {
        type: "Brand",
        parentID: 2222222,
        title: "Samsung",
        ID: 22222222,
        isSelected: false,
        isExpanded: false,
      },
    ],
  },
  {
    type: "Product",
    title: "Accessories",
    ID: 5,
    isSelected: false,
    isExpanded: false,
  },
];

export default mockData;
